export const DEV_USER_POOL_ID = "ENTER_YOUR_DEV_USERPOOL_ID";
export const DEV_USER_POOL_CLIENT_ID = "ENTER_YOUR_DEV_USERPOOL_CLIENT_ID";
export const DEV_DYNAMO_TABLE_NAME = "ENTER_DEV_TABLE_NAME";
export const DEV_REGION = "ENTER_DEV_REGION";
